import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Temp from "../public/temp.jpg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Oliver Turp | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.home__hero_wrap}>
          <div className={styles.home__hero_wrap_left}>
            <div className={styles.home__hero_wrap_left_text}>
              <h5 className={styles.home__hero_wrap_left_text_h5}>
                Hi, my name is
              </h5>
              <h1 className={styles.home__hero_wrap_left_text_h1}>
                Oliver Turp
              </h1>
              <h3 className={styles.home__hero_wrap_left_text_h3}>
                Your Website Is My Passion!
              </h3>
              <p className={styles.home__hero_wrap_left_text_p}>
                I’m A Web Designer & Developer With A Love For All Things
                Frontend! I’m based in the UK but work remotely with carefully
                selected clientele and I'm always on the look out for new
                opportunities!
              </p>
            </div>
            <button className={styles.home__cta}>
              <a href="#">
                <h5>Let's Work Together!</h5>
              </a>
            </button>
          </div>
          <div className={styles.home__hero_wrap_right}>
            <Image src={Temp} />
          </div>
        </div>
      </main>
    </>
  );
}
