import Head from "next/head";
import Image from "next/image";

import NavBar from "../components/Navbar";
import Footer from "../components/Footer";
import UIEG from "../components/UiExamples/UIEG";

const UiExamples = () => {
  return (
    <>
      <Head>
        <title>Oliver Turp | UI Examples</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <UIEG />
      <Footer />
    </>
  );
};

export default UiExamples;
