import Temp from "../Assets/Images/ProjectIcon_Blank.png";

const home__uiExamplesData = [
  {
    id: "001",
    section: "Header",
    type: "Horizontal",
    desc: "Enter Desc Here",
    image: Temp,
    link: "/header/horizontal",
  },
  {
    id: "002",
    section: "Header",
    type: "Drop Down",
    desc: "Enter Desc Here",
    image: Temp,
    link: "/header/dropdown",
  },
  {
    id: "003",
    section: "Header",
    type: "Hamburger",
    desc: "Enter Desc Here",
    image: Temp,
    link: "/header/hamburger",
  },
  {
    id: "004",
    section: "Images",
    type: "Gallery",
    desc: "Enter Desc Here",
    image: Temp,
    link: "/image/gallery",
  },
  {
    id: "005",
    section: "Images",
    type: "Carousel",
    desc: "Enter Desc Here",
    image: Temp,
    link: "/image/carousel",
  },
  {
    id: "006",
    section: "Contact",
    type: "MailTo",
    desc: "Enter Desc Here",
    image: Temp,
    link: "/contact/mailto",
  },
  {
    id: "007",
    section: "Contact",
    type: "Form",
    desc: "Enter Desc Here",
    image: Temp,
    link: "/contact/form",
  },
  {
    id: "008",
    section: "Footer",
    type: "Plain",
    desc: "Enter Desc Here",
    image: Temp,
    link: "/footer/plain",
  },
  {
    id: "009",
    section: "Footer",
    type: "Multi Line",
    desc: "Enter Desc Here",
    image: Temp,
    link: "/footer/multiline",
  },
  {
    id: "010",
    section: "Footer",
    type: "Directory",
    desc: "Enter Desc Here",
    image: Temp,
    link: "/footer/directory",
  },
  {
    id: "011",
    section: "Theme",
    type: "Static",
    desc: "Enter Desc Here",
    image: Temp,
    link: "/theme/static",
  },
  {
    id: "012",
    section: "Theme",
    type: "Toggle",
    desc: "Enter Desc Here",
    image: Temp,
    link: "/theme/toggle",
  },
];

export default home__uiExamplesData;
