import Temp from "../../public/temp.jpg";

const UIEG_Data = [
  {
    id: 1,
    section: "Header",
    type: "Horizontal",
    desc: "Enter Desc Here",
    image: Temp,
    link: "/sandbox/examples/header/horizontal",
  },
  {
    id: 2,
    section: "Header",
    type: "Drop Down",
    desc: "Enter Desc Here",
    image: Temp,
    link: "/sandbox/examples/header/dropdown",
  },
  {
    id: 3,
    section: "Header",
    type: "Hamburger",
    desc: "Enter Desc Here",
    image: Temp,
    link: "/sandbox/examples/header/hamburger",
  },
  {
    id: 4,
    section: "Images",
    type: "Gallery",
    desc: "Enter Desc Here",
    image: Temp,
    link: "/sandbox/examples/image/gallery",
  },
  {
    id: 5,
    section: "Images",
    type: "Carousel",
    desc: "Enter Desc Here",
    image: Temp,
    link: "/sandbox/examples/image/carousel",
  },
  {
    id: 6,
    section: "Contact",
    type: "MailTo",
    desc: "Enter Desc Here",
    image: Temp,
    link: "/sandbox/examples/contact/mailto",
  },
  {
    id: 7,
    section: "Contact",
    type: "Form",
    desc: "Enter Desc Here",
    image: Temp,
    link: "/sandbox/examples/contact/form",
  },
  {
    id: 8,
    section: "Footer",
    type: "Plain",
    desc: "Enter Desc Here",
    image: Temp,
    link: "/sandbox/examples/footer/plain",
  },
  {
    id: 9,
    section: "Footer",
    type: "Multi Line",
    desc: "Enter Desc Here",
    image: Temp,
    link: "/sandbox/examples/footer/multiline",
  },
  {
    id: 10,
    section: "Footer",
    type: "Directory",
    desc: "Enter Desc Here",
    image: Temp,
    link: "/sandbox/examples/footer/directory",
  },
  {
    id: 11,
    section: "Theme",
    type: "Static",
    desc: "Enter Desc Here",
    image: Temp,
    link: "/sandbox/examples/theme/static",
  },
  {
    id: 12,
    section: "Theme",
    type: "Toggle",
    desc: "Enter Desc Here",
    image: Temp,
    link: "/sandbox/examples/theme/toggle",
  },
];

export default UIEG_Data;
